"""Typed occupant interventions implemented as deterministic profile diffs."""

from __future__ import annotations

from dataclasses import dataclass, replace
from datetime import datetime, time, timedelta
from typing import Any

from hemm_core.manifest.constraints import MinEnergyUntil
from hemm_core.manifest.messages import ConstraintWindow
from hemm_core.sim.occupants.profile import ApplianceEvent, HouseholdProfile


@dataclass(frozen=True)
class ComfortOverride:
    """Slot-level room comfort override generated by a setpoint intervention."""

    zone: str
    min_temp_c: float
    max_temp_c: float
    when: str


@dataclass(frozen=True)
class InterventionResult:
    """Output of applying interventions."""

    profile: HouseholdProfile
    constraint_windows: list[ConstraintWindow]
    comfort_overrides: list[ComfortOverride]
    applied_ids: list[str]


def apply_interventions(profile: HouseholdProfile, interventions: list[dict[str, Any]] | None) -> InterventionResult:
    """Apply typed interventions as deterministic transforms."""
    current = profile
    windows: list[ConstraintWindow] = []
    comfort: list[ComfortOverride] = []
    applied: list[str] = []

    for spec in interventions or []:
        typ = spec.get("type")
        intervention_id = str(spec.get("id") or typ)
        if typ == "shift_load":
            current = _shift_load(current, spec)
            applied.append(intervention_id)
        elif typ == "setpoint":
            comfort.append(
                ComfortOverride(
                    zone=str(spec.get("zone", "living_room")),
                    min_temp_c=float(spec.get("setpoint_c", 18.0)),
                    max_temp_c=float(spec.get("max_temp_c", 24.0)),
                    when=str(spec.get("when", "presence == 0")),
                )
            )
            applied.append(intervention_id)
        elif typ == "ev_timing":
            window = _ev_constraint(current, spec, intervention_id)
            if window is not None:
                windows.append(window)
            applied.append(intervention_id)
        elif typ == "timer":
            current = _shift_load(current, spec)
            applied.append(intervention_id)
        else:
            msg = f"Unknown intervention type: {typ}"
            raise ValueError(msg)

    return InterventionResult(
        profile=current, constraint_windows=windows, comfort_overrides=comfort, applied_ids=applied
    )


def _shift_load(profile: HouseholdProfile, spec: dict[str, Any]) -> HouseholdProfile:
    appliance = str(spec.get("appliance", "dishwasher"))
    window = spec.get("to_window", {})
    earliest = _parse_time(str(window.get("earliest", "11:00")))
    latest = _parse_time(str(window.get("latest", "16:00")))
    slots = list(profile.slots)
    by_ts = {slot.timestamp: idx for idx, slot in enumerate(slots)}

    for idx, slot in enumerate(list(slots)):
        matching = [event for event in slot.appliance_events if event.appliance == appliance]
        if not matching:
            continue
        kept = [event for event in slot.appliance_events if event.appliance != appliance]
        slots[idx] = replace(slot, electric_appliances_w=0.0, appliance_events=kept)
        for event in matching:
            target_ts = _next_window_start(event.start, earliest, latest)
            target_idx = by_ts.get(target_ts)
            if target_idx is None:
                continue
            duration_slots = max(1, event.duration_minutes // profile.resolution_minutes)
            power_w = event.energy_kwh / (duration_slots * profile.resolution_minutes / 60.0) * 1000.0
            shifted = ApplianceEvent(
                appliance=event.appliance,
                start=target_ts,
                energy_kwh=event.energy_kwh,
                deadline_default=event.deadline_default,
                duration_minutes=event.duration_minutes,
                resource_use=list(event.resource_use),
                device_id=event.device_id,
            )
            for offset in range(duration_slots):
                j = target_idx + offset
                if j >= len(slots):
                    break
                extra_events = [shifted] if offset == 0 else []
                slots[j] = replace(
                    slots[j],
                    electric_appliances_w=slots[j].electric_appliances_w + power_w,
                    appliance_events=[*slots[j].appliance_events, *extra_events],
                    internal_gains_w=slots[j].internal_gains_w + power_w * 0.35,
                )
    return profile.with_slots(slots, source_suffix="interventions")


def _ev_constraint(profile: HouseholdProfile, spec: dict[str, Any], intervention_id: str) -> ConstraintWindow | None:
    device_id = str(spec.get("device_id", "ev_charger_garage"))
    energy_kwh = float(spec.get("energy_kwh", 12.0))
    deadline_local = _parse_time(str(spec.get("deadline_local", "07:00")))
    first = profile.start
    deadline = first.replace(hour=deadline_local.hour, minute=deadline_local.minute, second=0, microsecond=0)
    if deadline <= first:
        deadline += timedelta(days=1)
    return ConstraintWindow(
        window_id=f"occupants_{intervention_id}",
        device_id=device_id,
        deadline=deadline,
        requirement=MinEnergyUntil(min_energy_kwh=energy_kwh),
        priority_penalty=float(spec.get("priority_penalty", 6.0)),
        created_at=first,
    )


def _next_window_start(start: datetime, earliest: time, latest: time) -> datetime:
    candidate = start.replace(hour=earliest.hour, minute=earliest.minute, second=0, microsecond=0)
    latest_dt = start.replace(hour=latest.hour, minute=latest.minute, second=0, microsecond=0)
    if candidate <= start <= latest_dt:
        return start
    return candidate


def _parse_time(raw: str) -> time:
    hour, minute = raw.split(":", 1)
    return time(hour=int(hour), minute=int(minute))
